name: Push to server 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     -  name: Checkout repository
        uses: actions/checkout@v2

     - name: Deploy to server
       env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST:  147.93.94.206
          REMOTE_USER: root
       run: |
         echo "$SSH_PRIVATE_KEY"  > private.pem
         chmod  400 private.pem
         ssh -i private.pem -o "StrictHostKeyChecking no" $REMOTE_USER@$REMOTE_HOST " \
           cd nasa_gulf  &&  git pull  &&  npm i   && pm2 restart nasa_gulf "
